# Site settings
title: Thomas Mai | Toronto x BTM
description: Thomas Mai - Toronto-based Business Technology Management Student
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Thomas Mai
user_description: <p>Hey, I'm Thomas Mai. I am currently an undergraduate business student on a pursuit in a career in the business and technology sectors. I am currently attending <a href="http://www.ryerson.ca/">Ryerson University</a> in Toronto, Canada since September 2016 for the Bachelor of Commerce (B.Com) in Business Technology Management program offered by the <a href="http://www.ryerson.ca/tedrogersschool/">Ted Rogers School of Management</a>.</p>
user_title: Toronto-based Business Technology Management Student
email: contact@thomasmai.ca
github_username:  thomasmai
linkedin_username: thomastmai

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
